services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockhand.rule=Host(`${DOCKHAND_HOSTNAME}`)"
      - "traefik.http.routers.dockhand.entrypoints=websecure"
      - "traefik.http.routers.dockhand.tls=true"
      - "traefik.http.routers.dockhand.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dockhand.middlewares=authelia@docker"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DATA_DIR}/dockhand:/app/data
    profiles: 
      - dockhand
      - all
