services:
  xrdb:
    container_name: xrdb
    image: ghcr.io/ibbylabs/xrdb:${XRDB_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3000
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xrdb.rule=Host(`${XRDB_HOSTNAME?}`)"
      - "traefik.http.routers.xrdb.entrypoints=websecure"
      - "traefik.http.routers.xrdb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.xrdb.middlewares=authelia@docker"
      - "traefik.http.services.xrdb.loadbalancer.server.port=3000"
    volumes:
      - ${DOCKER_DATA_DIR}/xrdb:/app/data
    profiles:
      - xrdb
      - all